# Generated by Django 4.2.8 on 2023-12-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='userName', max_length=100)),
                ('firstname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='firstName', max_length=50)),
                ('lastname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='lastName', max_length=50)),
                ('address', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=300)),
                ('phone', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20)),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('role_id', models.IntegerField()),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
