# Generated by Django 4.2.8 on 2024-01-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Products',
        ),
    ]
